/**
 * Generated by scripts/fetch-map-assets.sh — do not edit by hand.
 * Regenerate with: REGION=middle-tennessee npm run map:fetch
 */

export const REGION_ID = 'middle-tennessee';
export const REGION_LABEL = 'Middle Tennessee';

/** Extent of the full-detail extract [west, south, east, north]. */
export const DETAIL_BOUNDS: [number, number, number, number] = [-87.80, 35.95, -86.50, 36.85];

/** Camera fence — the coarse context archive, so zooming out stays on-map. */
export const MAX_BOUNDS: [number, number, number, number] = [-125, 24, -66, 50];

/** Below this zoom the detail source is hidden and context shows through. */
export const DETAIL_MIN_ZOOM = 8;

export const INITIAL_VIEW = {
  longitude: -87.15,
  latitude: 36.40,
  zoom: 9.2,
} as const;
