#!/usr/bin/env bash
#
# Downloads the offline map assets into public/map/ and generates the matching
# region constants at src/map/region.ts.
#
# The app makes no network calls at runtime — every tile, glyph and elevation
# sample is served from public/map/. This script is the one-time (and only)
# step that touches the network.
#
# Both archives are PMTiles: a single file addressed via HTTP range requests,
# so there is no tile server to run. `pmtiles extract` pulls just our bounding
# box out of the remote planet archive rather than downloading the whole thing.
#
# Usage:
#   ./scripts/fetch-map-assets.sh              # region committed in region.ts
#   REGION=grand-canyon ./scripts/fetch-map-assets.sh
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Default to whatever region.ts is already configured for, so a fresh clone
# just runs `npm run map:fetch` and gets data matching the committed config.
# The two can otherwise silently disagree (wrong tiles under the camera).
default_region() {
  sed -n "s/^export const REGION_ID = '\(.*\)';/\1/p" "$ROOT/src/map/region.ts" 2>/dev/null
}
REGION="${REGION:-$(default_region)}"
REGION="${REGION:-los-angeles}"

# Each preset is: bbox(W,S,E,N) | center lng | center lat | zoom | label
# Keep the camera inside the bbox — outside it there are no tiles to draw.
case "$REGION" in
  los-angeles)
    BBOX="-119.0,33.5,-117.5,34.45"; LNG=-118.35; LAT=34.00; ZOOM=9.3
    LABEL="Los Angeles" ;;
  grand-canyon)
    BBOX="-113.2,34.5,-111.2,36.6"; LNG=-112.00; LAT=35.50; ZOOM=8.3
    LABEL="Grand Canyon" ;;
  nyc)
    BBOX="-74.35,40.45,-73.65,41.00"; LNG=-74.00; LAT=40.72; ZOOM=10.5
    LABEL="New York City" ;;
  # Fort Campbell (KY) down to Nashville — the 101st Airborne's home corridor.
  middle-tennessee)
    BBOX="-87.80,35.95,-86.50,36.85"; LNG=-87.15; LAT=36.40; ZOOM=9.2
    LABEL="Middle Tennessee" ;;
  interlaken)
    BBOX="7.55,46.45,8.15,46.80"; LNG=7.85; LAT=46.63; ZOOM=10.5
    LABEL="Interlaken" ;;
  *)
    echo "Unknown REGION '$REGION'." >&2
    echo "Expected one of: los-angeles, grand-canyon, nyc, middle-tennessee, interlaken" >&2
    exit 1 ;;
esac

# Protomaps publishes a rolling window of daily planet builds and prunes old
# ones, so a hardcoded date will 404 after a couple of weeks. Override when you
# need a reproducible build: BASEMAP_BUILD=20260719 ./scripts/fetch-map-assets.sh
BASEMAP_BUILD="${BASEMAP_BUILD:-$(date -u -d '2 days ago' +%Y%m%d)}"
BASEMAP_URL="https://build.protomaps.com/${BASEMAP_BUILD}.pmtiles"
DEM_URL="https://download.mapterhorn.com/planet.pmtiles"

# z14 is the basemap's native max. z11 on the DEM is a deliberate size tradeoff:
# z12 roughly triples the archive and hillshade overzooms cleanly.
BASEMAP_MAXZOOM="${BASEMAP_MAXZOOM:-14}"
DEM_MAXZOOM="${DEM_MAXZOOM:-11}"

# A `pmtiles extract` keeps only tiles overlapping its bbox, so at low zoom the
# detail archive is a single tile in empty space. This second, coarse archive
# covers the whole continent cheaply (~19MB at z7) and renders underneath, so
# zooming out shows a real map instead of a void.
CONTEXT_BBOX="${CONTEXT_BBOX:--125,24,-66,50}"
CONTEXT_MAXZOOM="${CONTEXT_MAXZOOM:-7}"
# Below this zoom the detail layers are hidden and context shows through.
DETAIL_MIN_ZOOM=8

PMTILES_VERSION="1.31.1"
OUT_DIR="$ROOT/public/map"

mkdir -p "$OUT_DIR"

# Prefer a system pmtiles if the user already has one; otherwise fetch the
# release binary into a temp dir that we clean up on exit.
if command -v pmtiles >/dev/null 2>&1; then
  PMTILES=pmtiles
else
  TMP_DIR="$(mktemp -d)"
  trap 'rm -rf "$TMP_DIR"' EXIT
  echo "==> Fetching pmtiles CLI v${PMTILES_VERSION}"
  curl -sSLf -o "$TMP_DIR/pmtiles.tar.gz" \
    "https://github.com/protomaps/go-pmtiles/releases/download/v${PMTILES_VERSION}/go-pmtiles_${PMTILES_VERSION}_Linux_x86_64.tar.gz"
  tar xzf "$TMP_DIR/pmtiles.tar.gz" -C "$TMP_DIR"
  PMTILES="$TMP_DIR/pmtiles"
fi

# Filenames are region-neutral so switching regions never touches app code.
echo "==> [${REGION}] Extracting basemap from ${BASEMAP_BUILD} (z<=${BASEMAP_MAXZOOM})"
"$PMTILES" extract "$BASEMAP_URL" "$OUT_DIR/basemap.pmtiles" \
  --bbox="$BBOX" --maxzoom="$BASEMAP_MAXZOOM"

echo "==> [${REGION}] Extracting terrain DEM (z<=${DEM_MAXZOOM})"
"$PMTILES" extract "$DEM_URL" "$OUT_DIR/terrain.pmtiles" \
  --bbox="$BBOX" --maxzoom="$DEM_MAXZOOM"

echo "==> Extracting low-zoom context basemap (z<=${CONTEXT_MAXZOOM})"
"$PMTILES" extract "$BASEMAP_URL" "$OUT_DIR/context.pmtiles" \
  --bbox="$CONTEXT_BBOX" --maxzoom="$CONTEXT_MAXZOOM"

# Generate the region constants rather than duplicating the bbox in TypeScript,
# where it could silently drift out of sync with the extracted tiles.
IFS=',' read -r W S E N <<< "$BBOX"
IFS=',' read -r CW CS CE CN <<< "$CONTEXT_BBOX"
cat > "$ROOT/src/map/region.ts" <<EOF
/**
 * Generated by scripts/fetch-map-assets.sh — do not edit by hand.
 * Regenerate with: REGION=${REGION} npm run map:fetch
 */

export const REGION_ID = '${REGION}';
export const REGION_LABEL = '${LABEL}';

/** Extent of the full-detail extract [west, south, east, north]. */
export const DETAIL_BOUNDS: [number, number, number, number] = [${W}, ${S}, ${E}, ${N}];

/** Camera fence — the coarse context archive, so zooming out stays on-map. */
export const MAX_BOUNDS: [number, number, number, number] = [${CW}, ${CS}, ${CE}, ${CN}];

/** Below this zoom the detail source is hidden and context shows through. */
export const DETAIL_MIN_ZOOM = ${DETAIL_MIN_ZOOM};

export const INITIAL_VIEW = {
  longitude: ${LNG},
  latitude: ${LAT},
  zoom: ${ZOOM},
} as const;
EOF

echo
echo "==> Done. Wrote src/map/region.ts and:"
du -sh "$OUT_DIR"/*.pmtiles
